# Generated by Django 5.1.4 on 2025-01-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calorieentry',
            options={},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={},
        ),
        migrations.RemoveField(
            model_name='calorieentry',
            name='meal_time',
        ),
        migrations.RemoveField(
            model_name='calorieentry',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='dailygoal',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='food',
            name='updated_at',
        ),
    ]
